export interface JobRecord {
  id: number
  title: string
  company: string
  location: string
  country: 'Taiwan' | 'Japan' | 'Korea'
  salaryMin: number
  salaryMax: number
  category: string
  experience: string
  shift: 'Day' | 'Night' | 'Rotating'
  gender: 'Any' | 'Male' | 'Female'
  housingSupport: boolean
  tags: string[]
  featured: boolean
  postedAt: string
  matchScore: number
}

export const jobRecords: JobRecord[] = [
  {
    id: 1,
    title: 'Senior Software Engineer',
    company: 'TechCorp Taipei',
    location: 'Taipei',
    country: 'Taiwan',
    salaryMin: 3500,
    salaryMax: 5000,
    category: 'Technology',
    experience: '3-5 years',
    shift: 'Day',
    gender: 'Any',
    housingSupport: true,
    tags: ['React', 'Node.js', 'AWS'],
    featured: true,
    postedAt: '2026-04-14',
    matchScore: 92,
  },
  {
    id: 2,
    title: 'Product Manager',
    company: 'DataSys Inc',
    location: 'Hsinchu',
    country: 'Taiwan',
    salaryMin: 2800,
    salaryMax: 4200,
    category: 'Management',
    experience: '5-7 years',
    shift: 'Day',
    gender: 'Any',
    housingSupport: false,
    tags: ['Product', 'Strategy', 'Leadership'],
    featured: false,
    postedAt: '2026-04-13',
    matchScore: 85,
  },
  {
    id: 3,
    title: 'UX/UI Designer',
    company: 'CreativeStudio',
    location: 'Taichung',
    country: 'Taiwan',
    salaryMin: 2200,
    salaryMax: 3500,
    category: 'Design',
    experience: '2-4 years',
    shift: 'Day',
    gender: 'Any',
    housingSupport: true,
    tags: ['Design', 'Figma', 'Web3'],
    featured: true,
    postedAt: '2026-04-12',
    matchScore: 88,
  },
  {
    id: 4,
    title: 'DevOps Engineer',
    company: 'Infrastructure Pro',
    location: 'Taipei',
    country: 'Taiwan',
    salaryMin: 3000,
    salaryMax: 4500,
    category: 'Technology',
    experience: '3-5 years',
    shift: 'Rotating',
    gender: 'Any',
    housingSupport: true,
    tags: ['Kubernetes', 'Docker', 'AWS'],
    featured: false,
    postedAt: '2026-04-11',
    matchScore: 90,
  },
  {
    id: 5,
    title: 'Factory Supervisor',
    company: 'NexManufacture',
    location: 'Taoyuan',
    country: 'Taiwan',
    salaryMin: 2100,
    salaryMax: 3000,
    category: 'Manufacturing',
    experience: '1-3 years',
    shift: 'Night',
    gender: 'Male',
    housingSupport: true,
    tags: ['Production', 'QA', 'Lean'],
    featured: false,
    postedAt: '2026-04-10',
    matchScore: 76,
  },
  {
    id: 6,
    title: 'Data Scientist',
    company: 'Analytics Hub',
    location: 'Taipei',
    country: 'Taiwan',
    salaryMin: 3200,
    salaryMax: 4800,
    category: 'Technology',
    experience: '2-4 years',
    shift: 'Day',
    gender: 'Any',
    housingSupport: false,
    tags: ['Python', 'ML', 'TensorFlow'],
    featured: true,
    postedAt: '2026-04-09',
    matchScore: 95,
  },
  {
    id: 7,
    title: 'Nursing Assistant',
    company: 'CarePoint Hospital',
    location: 'Kaohsiung',
    country: 'Taiwan',
    salaryMin: 1800,
    salaryMax: 2600,
    category: 'Healthcare',
    experience: '1-3 years',
    shift: 'Rotating',
    gender: 'Female',
    housingSupport: true,
    tags: ['Patient Care', 'Documentation'],
    featured: false,
    postedAt: '2026-04-08',
    matchScore: 74,
  },
  {
    id: 8,
    title: 'Warehouse Coordinator',
    company: 'LogiCore',
    location: 'Tainan',
    country: 'Taiwan',
    salaryMin: 1900,
    salaryMax: 2700,
    category: 'Logistics',
    experience: '0-2 years',
    shift: 'Day',
    gender: 'Any',
    housingSupport: false,
    tags: ['Inventory', 'Excel', 'Planning'],
    featured: false,
    postedAt: '2026-04-07',
    matchScore: 70,
  },
]
